# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blog post }
    admin.options:
        class: AppBundle\Admin\OptionsAdmin
        arguments: [~, AppBundle\Entity\Options, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Options }
    app.admin.entity_route_builder:
            class: AppBundle\Route\EntityRouterBuilder
            arguments:
                - "@sonata.admin.audit.manager"

